### ISSUE TITLE
fastmail-FolderBadgeControls not working

### ISSUE THREAD

**Issue by MelchiorGaspar** [michaelstepner/fastmail-FolderBadgeControls#1]
First off thx.. 
I am using Firefox v51.0.1 64bit and GreaseMonkey v3.10 on Windows 7 Ultimate 64bit

I installed the (v1.01) script from the linked website:
https://greasyfork.org/en/scripts/9461-fastmail-folder-badge-controls/code
but no config popup and no anything... :(

I have tried logging out and back in.. nope that didn't help...

**Comment by michaelstepner** [comment]
It's working for me in Firefox v51.0.1 64bit and GreaseMonkey v3.10 on OS X Sierra.

I can get to the config when I'm on the Fastmail website by going to: Tools > Greasemonkey > User script commands... > Folder badge configuration

But I am not actively maintaining this project, so if that doesn't work for you, I'm afraid I can't help. I'd welcome a pull request to fix any issues.

**Comment by MelchiorGaspar** [comment]
sorry my bad, I did a restart of Firefox and the popup came up...
how do I specify all folders... I have a lot and don't really want to name 100 folders name... will a wild card work? like * ?

**Comment by michaelstepner** [comment]
I didn't write any wildcard functionality, so I doubt that would work. It will probably require modifying the script.

I wrote the script without ever having used Javascript before, so it's possible you could get this done even easier than I did! 😄

**Comment by MelchiorGaspar** [comment]
loi thx ooh too bad... maybe u could add wildcards in maybe a future release if u ever choose to update it in the future ...

thx for the quick replies...
idk anything about js :(

**Comment by michaelstepner** [comment]
Thanks @MelchiorGaspar, glad you found it (*potentially*) useful!

**Comment by MelchiorGaspar** [comment]
yeah.. but it could be better if it had in the config the ability to switch to a number only display 
(new#/total#) as the use of words seems to clutter the UI a bit sorry... at last that is how it looks in the 
FastMail Classic UI

maybe u can add that as a 2nd future goal...

**Comment by michaelstepner** [comment]
ah, i also don't use the FastMail Classic UI.

in practice, my only goal for this project was to solve a frustration I was having. I put it up in case it's useful for others, but I don't plan to develop it any further unless I have a need for new features...

too bad it didn't work out for your use case.

**Comment by MelchiorGaspar** [comment]
ok thx none the less
